name: Release

permissions: write-all

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
            binary_postfix: ".exe"
          - os: windows-latest
            target: i686-pc-windows-msvc
            code-target: win32-ia32
            binary_postfix: ".exe"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
            binary_postfix: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            code-target: darwin-x64
            binary_postfix: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            code-target: darwin-arm64
            binary_postfix: ""
          
    name: release for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Configure Rust Target
        run: |
          rustup update
          rustup target add ${{ matrix.target }}
      - uses: actions/checkout@v3
      - name: Build release for ${{ matrix.target }}
        run: cargo build --release --target=${{ matrix.target }}
      - name: Zip and calculate Sha256 (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          7z a shutdown-scheduler-${{ steps.get_version.outputs.version }}-${{ matrix.code-target }}.zip  ./LICENSE ./README.md ./target/${{ matrix.target }}/release/ugdown${{ matrix.binary_postfix }}
          sha256sum shutdown-scheduler-${{ steps.get_version.outputs.version }}-${{ matrix.code-target }}.zip > shutdown-scheduler-${{ steps.get_version.outputs.version }}-${{ matrix.code-target }}.zip.sha256sum
      - name: Zip and calculate Sha256 (Not Windows)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          tar czvf shutdown-scheduler-${{ steps.get_version.outputs.version }}-${{ matrix.code-target }}.tar.gz README.md LICENSE -C ./target/${{ matrix.target }}/release shutdown-scheduler${{ matrix.binary_postfix }}
          shasum -a 256 shutdown-scheduler-${{ steps.get_version.outputs.version }}-${{ matrix.code-target }}.tar.gz > shutdown-scheduler-${{ steps.get_version.outputs.version }}-${{ matrix.code-target }}.tar.gz.sha256sum 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: shutdown-scheduler-*[.zip][.tar.gz]*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true